GET http://localhost:5000/users
Content-Type: application/json

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "fname":"vivek",
  "lname":"kumar",
  "email":"vivekmethew8@gmail.com",
  "password":"123456",
  "phone":"9718546885"
}
